# Generated by Django 4.2.20 on 2025-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0002_evaluacionlecturaindividual_fecha_lectura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionlectura',
            name='textos_leidos',
            field=models.IntegerField(default=0),
        ),
    ]
