# Generated by Django 4.2.20 on 2025-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0003_alter_evaluacionlectura_textos_leidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionlectura',
            name='porcentaje',
            field=models.FloatField(default=0),
        ),
    ]
