# Generated by Django 4.2.20 on 2025-05-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0004_alter_evaluacionlectura_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaEnCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_texto', models.CharField(max_length=50)),
                ('titulo_lectura', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacionescl.registrousuarios')),
            ],
            options={
                'unique_together': {('usuario', 'tipo_texto')},
            },
        ),
    ]
