# Generated by Django 4.2.20 on 2025-08-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0005_lecturaencurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroadmin',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decirlo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registrousuarios',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decirlo')], max_length=1, null=True),
        ),
    ]
