# Generated by Django 4.2.20 on 2025-08-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0006_registroadmin_sexo_registrousuarios_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroadmin',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decirlo')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrousuarios',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiero no decirlo')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
