# Generated by Django 4.2.20 on 2025-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0007_alter_registroadmin_sexo_alter_registrousuarios_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_texto', models.CharField(choices=[('Argumentativo', 'Argumentativo'), ('Descriptivo', 'Descriptivo'), ('Expositivo', 'Expositivo'), ('Narrativo', 'Narrativo')], max_length=50)),
                ('archivo_pdf', models.FileField(upload_to='bancotext/')),
                ('conteo_palabras', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='palabras_por_minuto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='tiempo_lectura_segundos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
