# Generated by Django 5.2.7 on 2025-11-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0008_lectura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturaencurso',
            name='en_pausa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturaencurso',
            name='segundos_acumulados',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lecturaencurso',
            name='ultimo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
