# Generated by Django 5.2.7 on 2025-11-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0009_lecturaencurso_en_pausa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='porcentaje_final',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
